Shifting deployment model.

diff --git a/roles/conan-deploy/templates/start-server.sh.j2 b/roles/conan-deploy/templates/start-server.sh.j2
--- a/roles/conan-deploy/templates/start-server.sh.j2
+++ b/roles/conan-deploy/templates/start-server.sh.j2
@@ -7,16 +7,18 @@ modpath="$basepath/ConanSandbox/Mods"
 modlist="$modpath/modlist.txt"
 modids="$basepath/modids.txt"
 
-# Install/Update Mods
-steamcmd="/usr/games/steamcmd +@sSteamCmdForcePlatformType windows +force_install_dir $tempmodpath +login anonymous"
-for mod in `cat $modids`; do
-  echo "Downloading mods."
-  steamcmd+=" +workshop_download_item 440900 $mod"
-  # if ! /usr/games/steamcmd +@sSteamCmdForcePlatformType windows +force_install_dir $tempmodpath +login anonymous +workshop_download_item 440900 $mod +exit; then
-  #   echo "Failed to download mod from Steam: $mod"
-  #   exit 1s
-  # fi
-done
-steamcmd+=" +exit"
-echo $steamcmd
-# /usr/games/steamcmd +@sSteamCmdForcePlatformType windows +force_install_dir /home/conan/exiles/modtmp +login anonymous +workshop_status 440900 880454836 +exit
+# Construct the Steam command to download all the mods in a single command.
+steam_command(){
+  steamcmd="/usr/games/steamcmd +@sSteamCmdForcePlatformType windows +force_install_dir $tempmodpath +login anonymous"
+  for mod in `cat $modids`; do
+    steamcmd+=" +workshop_download_item 440900 $mod"
+  done
+  steamcmd+=" +workshop_status 440900 +exit"
+}
+
+# Download mods.
+echo "Downloading mods from Steam."
+if ! eval $steamcmd; then
+  echo "Failed to download steam mods from workshop"
+  exit 1
+fi
